theme: jekyll-theme-minimal
title: artifacts
description: thoughts and things I've learned along the way ðŸ‘‹
show_downloads: False
include:
  - tom-circuit-path.html

navigation:
  - title: home
    url: /
  - title: about
    url: about
  - title: deconstructing theory of mind in large language models
    url: tom-interpretability
  - title: towards better mental health detection
    url: llms-mental-health
  - title: deep learning can solve non-trivial problems in nlp
    url: setup
  - title: finding similarities between friends using shallow & deep nlp
    url: finding-similarities-between-friends
  - title: visualizations & machine learning
    url: visualization-ml
  - title: millennial noir
    url: millennial-noir
